const Colors = {
  Rosewood:"#43302E",
  DarkGreen:"#013220",
  OceanBlue:"#93E9BE",
  DarkEclipse:"#000000",
  Mushroom: "#AC9362",
  Eggplant:"#483248",
  OceanStorm: "#76736e",
  Eclipse: "#000080",
  DesertSage: "#8A9A5B",
  FanaticTeal: "#008080",
  DarkBlue: "#00008B",
  Carbon: "#625D5D",
  Mint: "#C2E5D3",
  none: "",
  Ether: '#949AA7', 
  PirateBlack: '#585452',
  Black: "#000000",
  Tan: "#AC9362",
  Silver: "#C0C0C0",
  White: "#FFFFFF",
  Lime: "#32CD32",
  DarkGray: "#625D5D",
  RedOrange: "#FF5349",
  DarkRed: "#8b0000",
  Lichen: undefined,
  Orange: undefined,
  Charcoal: undefined,
  CharcoalOrange: undefined,
  LichenCharcoal: '#3E461C',
  LemonCurry: undefined,
  Turquoise: undefined,
  TwilightSmoke: undefined,
  Oxide: undefined,
  Graphite: undefined,
  SedonaSmoke: undefined,
  Bluebird: undefined,
  Smolder: undefined,
  GoodnightGrey: undefined,
  GreenGray: undefined,
  Olive: undefined,
  LightGreyGold: undefined,
  Orange: undefined,
  GrayOrange: undefined,
  Gold: undefined,
  Gray: undefined,
  PacificBlue: undefined,
  Bimini: undefined,
  Alpine: undefined
}

export default Colors;